name: lokalsetor
description: Flutter local database based on sharedpreference.
version: 0.0.2
repository: https://github.com/yuudinwah/lokalsetor.git
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  shared_preferences: ^2.0.13
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true